default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: localhost
  username: postgres
  password: postgres

development:
  <<: *default
  database: myblogs_development
test:
  <<: *default
  database: myblogs_test

production:
  <<: *default
  database: myblogs_production
